# Generated by Django 4.2.4 on 2023-08-25 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0002_acessório_cor_veiculo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Acessório",
            new_name="Acessorio",
        ),
        migrations.RemoveField(
            model_name="marca",
            name="nacionalidade",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="nome",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="Acessorio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="garagem.acessorio",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculo",
            name="Cor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="garagem.cor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "Categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelo",
                        to="garagem.categoria",
                    ),
                ),
                (
                    "Marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelo",
                        to="garagem.marca",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="veiculo",
            name="Modelo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="garagem.modelo",
            ),
            preserve_default=False,
        ),
    ]
