# Generated by Django 4.2.5 on 2023-09-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0002_veiculo_capa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessório", "verbose_name_plural": "Acessórios"},
        ),
        migrations.RenameField(
            model_name="modelo",
            old_name="Categoria",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="modelo",
            old_name="Marca",
            new_name="marca",
        ),
        migrations.RenameField(
            model_name="veiculo",
            old_name="Cor",
            new_name="cor",
        ),
        migrations.RenameField(
            model_name="veiculo",
            old_name="Modelo",
            new_name="modelo",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="Acessorio",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="capa",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="acessorio",
            field=models.ManyToManyField(
                related_name="veiculos", to="garagem.acessorio"
            ),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
